{
package durationparser
}

Duration <- sign:Sign? segments:Segment+ EOF {
	return Result{Sign: sign, Segments: segments.([]any)}, nil
}

Sign <- [-+] {
	return string(c.text), nil
}

Segment <- digits:Digits unit:Unit {
	return Segment{Digits: digits.(string), Unit: unit.(string)}, nil
}

Digits <- [0-9.]+ {
	return string(c.text), nil
}

Unit <- ("ms" / "us" / "µs" / "ns" / [a-z]) {
	return string(c.text), nil
}

EOF <- !.
